site_name: My Docs
theme:
  name: material
  # custom_dir: overrides
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  # logo: https://fastapi.tiangolo.com/img/icon-white.svg
  # favicon: https://fastapi.tiangolo.com/img/favicon.png
  language: zh
repo_name: ponponon/nie
repo_url: https://github.com/ponponon/nie
